create table if not exists public.draws (
  id bigint generated by default as identity primary key,
  games jsonb not null,
  locked_numbers smallint[] not null default '{}',
  created_at timestamptz not null default now(),
  constraint games_is_array check (jsonb_typeof(games) = 'array')
);

alter table public.draws enable row level security;

revoke all on table public.draws from anon, authenticated;
grant select, insert on table public.draws to service_role;
grant usage, select on sequence public.draws_id_seq to service_role;

create index if not exists draws_created_at_idx
  on public.draws (created_at desc);
